"""
safe_paths.py - the only place allowed to turn a piece of stored data
(a bill number, an uploaded file name) into a path on disk.

Why this matters in an offline desktop app:

  A bill number is normally generated by the app and is always eight
  digits, so building "data/bills/<bill_number>.pdf" from it looks safe.
  But bill numbers do NOT only come from the app - they also arrive
  inside .bbak / .db archive files that get imported from a pendrive,
  and those files are just SQLite databases that anyone can edit with a
  free tool. A bill number of "..\\..\\..\\Windows\\System32\\config" or
  "CON" turns an innocent "open this bill's PDF" click into writing or
  launching something entirely different.

  The old code guarded this with .replace("/", "-"), repeated in three
  files. That misses the Windows separator "\\", "..", drive letters,
  alternate data streams (":") and reserved device names. This module
  replaces all three copies.
"""

import os
import re

# Windows refuses (or does something surprising with) these names no
# matter what extension follows them.
_RESERVED_WINDOWS_NAMES = {
    "CON", "PRN", "AUX", "NUL",
    *(f"COM{i}" for i in range(1, 10)),
    *(f"LPT{i}" for i in range(1, 10)),
}

_UNSAFE_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')

MAX_FILENAME_LENGTH = 100


def safe_filename_component(value, fallback="unnamed"):
    """Reduces arbitrary text to something that can only ever be a single
    file name inside a directory we choose - never a path, never a parent
    directory, never a device.

    Returns `fallback` rather than raising when nothing usable survives,
    so a corrupt row degrades to an oddly-named file instead of crashing
    the screen that listed it.
    """
    text = str(value or "").strip()

    # Take only the last component: even if this arrived as a full path,
    # everything before the final separator is discarded.
    text = text.replace("\\", "/").split("/")[-1]

    text = _UNSAFE_CHARS.sub("-", text)
    text = text.strip(" .")           # trailing dots/spaces are stripped by Windows anyway
    text = re.sub(r"-{2,}", "-", text)

    if not text or set(text) <= {".", "-"}:
        return fallback

    stem = text.split(".")[0].upper()
    if stem in _RESERVED_WINDOWS_NAMES:
        text = "_" + text

    if len(text) > MAX_FILENAME_LENGTH:
        text = text[:MAX_FILENAME_LENGTH]

    return text or fallback


def bill_pdf_filename(bill_number):
    """The single definition of a bill's PDF file name. Every screen that
    opens, generates or looks for a bill PDF goes through here, so they
    can never disagree about where the file is."""
    return safe_filename_component(bill_number, fallback="bill") + ".pdf"


def bill_pdf_path(output_dir, bill_number):
    """Builds the full path AND proves it stayed inside output_dir.

    The containment check is belt-and-braces on top of
    safe_filename_component - it means that even if that function is
    changed carelessly later, a traversal still cannot escape the bills
    folder.
    """
    return resolve_within(output_dir, bill_pdf_filename(bill_number))


def resolve_within(base_dir, *parts):
    """Joins parts onto base_dir and raises ValueError if the result
    lands outside base_dir. Use for any path assembled from stored data."""
    base = os.path.abspath(base_dir)
    candidate = os.path.abspath(os.path.join(base, *parts))
    if not is_within(base, candidate):
        raise ValueError("Refusing to use a file path outside the application's own folder.")
    return candidate


def is_within(base_dir, candidate):
    """True when `candidate` is base_dir itself or sits underneath it.
    Uses os.path.commonpath rather than startswith, which would treat
    'data-old' as being inside 'data'."""
    try:
        base = os.path.abspath(base_dir)
        target = os.path.abspath(candidate)
        return os.path.commonpath([base, target]) == base
    except (ValueError, OSError):
        # Different drives on Windows raise ValueError - which is itself
        # the answer: not inside.
        return False


# ---------------- UPLOADED / IMPORTED FILES ----------------

ALLOWED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".bmp"}
ALLOWED_BACKUP_EXTENSIONS = {".bbak", ".db", ".sqlite", ".sqlite3", ".bbakx"}

MAX_LOGO_BYTES = 5 * 1024 * 1024          # 5 MB
MAX_LOGO_PIXELS = 8000                     # per side
MAX_BACKUP_BYTES = 500 * 1024 * 1024       # 500 MB


def check_upload(path, allowed_extensions, max_bytes, kind="file"):
    """Extension + size gate applied before a chosen file is read at all.

    The file-picker's own filter is only a convenience: on Windows a user
    can type a name and pick anything, so the filter is not a control.
    This is.
    """
    if not path or not os.path.isfile(path):
        raise ValueError(f"That {kind} could not be found.")

    ext = os.path.splitext(path)[1].lower()
    if ext not in allowed_extensions:
        allowed = ", ".join(sorted(allowed_extensions))
        raise ValueError(f"Only these {kind} types are allowed: {allowed}")

    size = os.path.getsize(path)
    if size == 0:
        raise ValueError(f"That {kind} is empty.")
    if size > max_bytes:
        raise ValueError(
            f"That {kind} is too large ({size / 1024 / 1024:.1f} MB). "
            f"The limit is {max_bytes // 1024 // 1024} MB."
        )
    return ext


def validate_image_file(path):
    """Confirms the file really is an image by decoding it, not by
    trusting its extension - a renamed .exe passes an extension check but
    fails here. Returns the normalized extension to save it under.

    PIL's verify() must be followed by a fresh open() to actually load,
    which is why the file is opened twice.
    """
    from PIL import Image  # imported lazily: keeps this module usable without Pillow

    ext = check_upload(path, ALLOWED_IMAGE_EXTENSIONS, MAX_LOGO_BYTES, kind="image")

    try:
        with Image.open(path) as probe:
            probe.verify()
    except Exception:
        raise ValueError("That file isn't a readable image. Please choose a PNG or JPG.")

    try:
        with Image.open(path) as img:
            width, height = img.size
            fmt = (img.format or "").upper()
    except Exception:
        raise ValueError("That file isn't a readable image. Please choose a PNG or JPG.")

    if fmt not in ("PNG", "JPEG", "WEBP", "BMP"):
        raise ValueError("Only PNG, JPG, WEBP or BMP images can be used as a logo.")

    # A "decompression bomb": a tiny file that expands to a huge bitmap
    # and exhausts memory when the preview is drawn.
    if width > MAX_LOGO_PIXELS or height > MAX_LOGO_PIXELS:
        raise ValueError(
            f"That image is too big ({width}x{height} pixels). "
            f"Please use one no larger than {MAX_LOGO_PIXELS}x{MAX_LOGO_PIXELS}."
        )
    if width == 0 or height == 0:
        raise ValueError("That image has no content.")

    return {".JPEG": ".jpg"}.get("." + fmt, "." + fmt.lower())


def validate_backup_file(path):
    """Size/extension gate plus a magic-header check that the file really
    is a SQLite database, before any SQL is run against it."""
    check_upload(path, ALLOWED_BACKUP_EXTENSIONS, MAX_BACKUP_BYTES, kind="backup file")

    with open(path, "rb") as fh:
        header = fh.read(16)

    if header.startswith(b"BBAKX1"):
        return "encrypted"
    if header.startswith(b"SQLite format 3\x00"):
        return "sqlite"

    raise ValueError(
        "That file isn't a Balaji backup file.\n\n"
        "Choose a .bbak or .db file created by this app's Backup or Archive button."
    )
